steps:

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK 3.1'
  inputs:
    version: '3.1.x'
- task: UseDotNet@2
  displayName: 'Install .NET SDK 5'
  inputs:
    version: '5.x'    
- task: UseDotNet@2
  displayName: 'Install .NET SDK 6'
  inputs:
    version: '6.x'  
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet 5.4'
  inputs:
    versionSpec: '5.4.x'
